spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS}
      routes:
        - id: ${ACCOUNTS_ROUTE_ID}
          uri: ${ACCOUNTS_ROUTE_URI}
          predicates:
            - Path=${ACCOUNTS_ROUTE_PREDICATE}
        - id: ${AUTH_ROUTE_ID}
          uri: ${AUTH_ROUTE_URI}
          predicates:
            - Path=${AUTH_ROUTE_PREDICATE}
        - id: ${MEETING_ROUTE_ID}
          uri: ${MEETING_ROUTE_URI}
          predicates:
            - Path=${MEETING_ROUTE_PREDICATE}

server:
  port: ${PORT}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG