spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS}
      routes:
        - id: ${MEETING_ROUTE_ID}
          uri: ${MEETING_SERVICE_URL}
          predicates:
            - Path=${MEETING_SERVICE_PREDICATE}
